### ISSUE TITLE
can't download to chrome

### ISSUE THREAD

**Issue by comfortablemilk4454** [ldx23/redown-redgifs-downloader#1]
downloaded from latest release (right clicked link -> save link as), but can't add the extension:

https://github.com/user-attachments/assets/ed34fb23-8a37-4606-942d-a0768701cb14

any ideas?

**Comment by ozindfw** [comment]
I have the same issue with Chrome Version 126.0.6478.183 (Official Build) (64-bit) and Brave 
[Version 1.68.128 Chromium: 127.0.6533.73 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by ldx23** [comment]
Okay, I'm looking into it

**Comment by ozindfw** [comment]
OK, figured out I have to be in "Developer Mode" on the extensions page to try this, but still no luck. I get: "Package is invalid: 'CRX_SIGNATURE_VERIFICATION_FAILED'.

**Comment by ozindfw** [comment]
thanks!

**Comment by ldx23** [comment]
@ComfortableMilk4454 @ozindfw 
I've fixed the error, the modified file is in the same (v0.69.2) release.
Tell me if this works

**Comment by ozindfw** [comment]
I can now install it, but I can't actually enable it.  

The On/off button is grayed out and inactive.  I don't see any error messages. I can toggle to on state of my other extensions (Google Docs Offline and password manager)

**Comment by ldx23** [comment]
According to [chrome](https://support.google.com/chrome_webstore/answer/2811969?visit_id=638575151822998393-3848790426&p=ui_remove_non_cws_extensions&hl=en&rd=2), you can't use a local `.crx` directly. 

Solutions:
1. Move away from chrome, which everyone seems to be doing for obvious reasons. There are many great options such as Opera GX, Brave, Vivaldi, Firefox ofc, Edge (seems to be kinda okay).
2. If staying on chrome, you will need to unpack/unzip the extension into a local folder and then drag and drop that onto the extensions page.

**Comment by ozindfw** [comment]
I'd tried both Chrome and Brave.  Brave has issues with Redgifs.  

I installed Opera and the plugin is showing in the extensions page, but I don't get anything new on the menu when I right click on a video.  

Save Video As is greyed out as well, but I expected it to be. 

BTW, the screencap images on the readme seem to be gone.

**Comment by ldx23** [comment]
It adds a download icon on the right hand side buttons of each video, which you can right click and "save linked content as"

This was visible in the screenshots in the readme... well,,,. 

I've added a new screenshot, removed the broken ones and updated the readme instructions.
